"use client"

import type { ComponentType } from "react"
import {
  // Sidebar / panel
  LayoutDashboard,
  GalleryHorizontal,
  Images,
  Info,
  MessageCircleQuestionMark,
  Sparkles,
  Menu,
  PanelsTopLeft,
  Search,
  Share2,
  House,
  FileText,
  Settings,
  FolderOpen,
  MousePointerClick,
  Trash2,
  Inbox,
  MessageSquare,
  // "Neden Aden" ve olası kullanıcı seçimleri (konaklama bağlamı)
  Waves,
  BellRing,
  CarFront,
  ShieldCheck,
  Users,
  MapPin,
  MessageCircle,
  HeartHandshake,
  Star,
  Heart,
  Wifi,
  Coffee,
  Bath,
  BedDouble,
  Trees,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Car,
  Phone,
  Mail,
  Instagram,
  Facebook,
  Check,
  CircleCheck,
  Award,
  Gift,
  Utensils,
  Tv,
  Wind,
  Droplets,
  Mountain,
  Camera,
  Key,
  Clock,
  Calendar,
  Home,
  ParkingCircle,
  Wine,
  Trophy,
  Youtube,
  Twitter,
  Linkedin,
  Send,
  Github,
  Circle,
} from "lucide-react"

/**
 * İsimle lucide ikonu render eder.
 *
 * ÖNEMLİ: Dinamik `icons` barrel lookup'ı (`import { icons }`) sunucu ve client
 * bundle'larında FARKLI çözülüp hydration uyuşmazlığına ("server rendered HTML
 * didn't match the client") yol açıyor. Bu yüzden burada STATİK explicit
 * import'lardan kurulu, iki tarafta da birebir aynı olan bir registry kullanılır.
 * Kayıtta olmayan isimler `Circle` ile karşılanır.
 */
type IconProps = { className?: string }

const REGISTRY: Record<string, ComponentType<IconProps>> = {
  LayoutDashboard,
  GalleryHorizontal,
  Images,
  Info,
  MessageCircleQuestionMark,
  Sparkles,
  Menu,
  PanelsTopLeft,
  Search,
  Share2,
  House,
  FileText,
  Settings,
  FolderOpen,
  MousePointerClick,
  Trash2,
  Inbox,
  MessageSquare,
  Waves,
  BellRing,
  CarFront,
  ShieldCheck,
  Users,
  MapPin,
  MessageCircle,
  HeartHandshake,
  Star,
  Heart,
  Wifi,
  Coffee,
  Bath,
  BedDouble,
  Trees,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Car,
  Phone,
  Mail,
  Instagram,
  Facebook,
  Check,
  CircleCheck,
  Award,
  Gift,
  Utensils,
  Tv,
  Wind,
  Droplets,
  Mountain,
  Camera,
  Key,
  Clock,
  Calendar,
  Home,
  ParkingCircle,
  Wine,
  Trophy,
  Youtube,
  Twitter,
  Linkedin,
  Send,
  Github,
  Circle,
}

export function LucideIcon({
  name,
  className,
  fallback = "Circle",
}: {
  name: string
  className?: string
  fallback?: string
}) {
  const Cmp = REGISTRY[name] ?? REGISTRY[fallback] ?? Circle
  return <Cmp className={className} />
}
